### ISSUE TITLE
Reading a schema file that has triple quotes?

### ISSUE THREAD

**Issue by gregarican** [graphql-dotnet/parser#81] opened 2020-08-03 18:19 UTC
So I have a schema file. With comments encased in triple quotes. Trying to read in the file like this:
` var schemaTxt = File.ReadAllText(@".\shopify.graphql");
            var schema = Schema.For(schemaTxt); `
When I do so the first line with triple quotes is throwing an exception. Is there an option I can configure to treat these as comments and ignore them?

For example, """Marks an element of a GraphQL schema as having restricted access."""

**Comment by sungam3r** [comment] 2020-08-16 14:10
Possible duplicate of #33.

**Comment by sungam3r** [comment] 2021-11-09 22:00
Support for descriptions was added in #132

**Closed by sungam3r** 2021-11-09 22:00 UTC
Labels: duplicate, enhancement, spec compliance
